builds:
  arise-bitcoind:
    instructions:
      - FROM debian:stable-slim AS builder
      - RUN apt-get update
      - RUN apt-get install -y autoconf bsdmainutils build-essential git libboost-all-dev libtool pkg-config
      - WORKDIR /usr
      - RUN git clone --depth 1 --branch v27.1 https://github.com/bitcoin/bitcoin.git
      - RUN cd bitcoin && ./autogen.sh && ./configure && make -j4
      - FROM debian:stable-slim AS runner
      - WORKDIR /usr/app
      - RUN apt-get update
      - RUN apt-get install -y libevent-dev
      - COPY --from=builder /usr/bitcoin/src/bitcoind /usr/app/bitcoind
      - COPY --from=builder /usr/bitcoin/src/bitcoin-cli /usr/app/bitcoin-cli
      - ENV PATH=$PATH:/usr/app
      - RUN mkdir -p /home/bitcoin/.bitcoin
      - VOLUME ["/home/bitcoin/.bitcoin"]
      - EXPOSE 8332 28332 28333
      - ENTRYPOINT ["/usr/app/bitcoind"]
network: arise
services:
  arise-bitcoind:
    command:
      # - -rpcauth=arise:0a17eed40accdd0f2271a548547ec9bb$b269b686f2ad7ccf0b5ea3450e0687dc1a90846d3828811ad0d570de83b65f4c
      - -daemon=1
      - -datadir=/home/bitcoin/.bitcoin
      - -dnsseed=0
      - -listen=1
      - -listenonion=1
      - -server=1
      - -txindex=1
      - -blockfilterindex=1
      - -rest=1
      - -rpcallowip=127.0.0.1
      - -rpcallowip=10.0.0.0/8
      - -rpcallowip=192.168.0.0/16
      - -rpcallowip=172.0.0.0/8
      - -rpcbind=0.0.0.0
      - -rpcport=8332
      - -rpcservertimeout=120
      - -rpcuser=arise
      - -rpcpassword=arise
      - -rpcworkqueue=128
      - -upnp=0
      - -whitelist=127.0.0.1
      - -zmqpubrawblock=tcp://0.0.0.0:28332
      - -zmqpubrawtx=tcp://0.0.0.0:28333
    image: arise-bitcoind
    ports:
      - 8332:8332
      - 28332:28332
      - 28333:28333
