builds:
  arise-bitcoind:
    instructions: &baseInstructions
      - FROM debian:stable-slim AS builder
      - RUN apt-get update
      - RUN apt-get install -y autoconf bsdmainutils build-essential git libboost-all-dev libtool pkg-config
      - WORKDIR /usr
      - RUN git clone --depth 1 --branch v27.1 https://github.com/bitcoin/bitcoin.git
      - RUN cd bitcoin && ./autogen.sh && ./configure && make -j4
      - FROM debian:stable-slim AS runner
      - WORKDIR /usr/app
      - RUN apt-get update
      - RUN apt-get install -y libevent-dev
      - COPY --from=builder /usr/bitcoin/src/bitcoind /usr/app/bitcoind
      - COPY --from=builder /usr/bitcoin/src/bitcoin-cli /usr/app/bitcoin-cli
      - ENV PATH=$PATH:/usr/app
      - RUN mkdir -p /home/bitcoin/.bitcoin
      - VOLUME ["/home/bitcoin/.bitcoin"]
  arise-mainnet:
    instructions:
      - << *baseInstructions
      - EXPOSE 8332 8333
      - ENTRYPOINT ["/usr/app/bitcoind"]
  arise-signet:
    instructions:
      - << *baseInstructions
      - EXPOSE 38332 38333
      - ENTRYPOINT ["/usr/app/bitcoind"]
  arise-testnet:
    instructions:
      - << *baseInstructions
      - EXPOSE 18332 18333
      - ENTRYPOINT ["/usr/app/bitcoind"]
  arise-testnet4:
    instructions:
      - << *baseInstructions
      - EXPOSE 48332 48333
      - ENTRYPOINT ["/usr/app/bitcoind"]
network: arise
services:
  arise-bitcoind:
    command: &baseCommand
      - -daemon=1
      - -datadir=/home/bitcoin/.bitcoin
      - -dnsseed=0
      - -listen=1
      - -listenonion=1
      - -server=1
      - -txindex=1
      - -blockfilterindex=1
      - -rest=1
      - -rpcallowip=127.0.0.1
      - -rpcallowip=10.0.0.0/8
      - -rpcallowip=192.168.0.0/16
      - -rpcallowip=172.0.0.0/8
      - -rpcbind=0.0.0.0
      - -rpcservertimeout=120
      - -rpcpassword=${ARISE_RPCPASS}
      - -rpcuser=${ARISE_RPCUSER}
      - -rpcworkqueue=128
      - -upnp=0
      - -whitelist=127.0.0.1
    image: arise-bitcoind
    ports:
      - 0:0
  arise-mainnet:
    command:
      - << *baseCommand
      - -port=8333
      - -rpcport=8332
    image: arise-mainnet
    ports:
      - 8332:8332
      - 8333:8333
  arise-signet:
    command:
      - << *baseCommand
      - -port=38333
      - -rpcport=38332
      - -signet
    image: arise-signet
    ports:
      - 38332:38332
      - 38333:38333
  arise-testnet:
    command:
      - << *baseCommand
      - -port=18333
      - -rpcport=18332
      - -testnet
    image: arise-testnet
    ports:
      - 18332:18332
      - 18333:18333
  arise-testnet4:
    command:
      - << *baseCommand
      - -port=48333
      - -rpcport=48332
      - -testnet4
    image: arise-testnet4
    ports:
      - 48332:48332
      - 48333:48333
